### PR TITLE
controller/v3: wire new resource set

### PR DESCRIPTION
**Pull request by MarcelMue**
twoards https://github.com/giantswarm/giantswarm/issues/3390

### CODE REVIEW

**Comment by MarcelMue** [comment]
I am not 100% certain about this, but I believe I didn't miss anything.

**Comment by xh3b4sd** [comment]
It looks like the changelogs in `v2` are stale. So we created a new version without having any changes of the former version reflected in its changelog. What went wrong here?

**Comment by MarcelMue** [comment]
Discussion ( https://gigantic.slack.com/archives/C2MS2VB37/p1531209641000220 ) was to have secret management in its own version for chart-operator.
Uncertain why the changelog in v2 is stale. IMO there should be atleast one change in the v2 changelog.
cc @rossf7

**Comment by rossf7** [comment]
Yes changelog is v2 is stale. That's my bad I'll fix. 

But imports look wrong here. e.g. https://github.com/giantswarm/chart-operator/blob/4027f0983b6d4a8883c593252ed417ca4a077c24/service/controller/v3/resource/chart/create.go

Marcel, did you use the bash magic to update the imports?

https://github.com/giantswarm/giantswarm/wiki/Releases:-Creating-New-VersionBundle

**Comment by MarcelMue** [comment]
I was not aware of the bash magic (forgot), I'll fix this.

**Pull request merged**
