### PR TITLE
Enable CNI app installation

### PR DESCRIPTION
**Pull request by kubasobon**
Towards https://github.com/giantswarm/giantswarm/issues/16283

:construction_worker: This branch should **not** be merged. It serves as a base for CAPI release with modified `chart-operator`. 

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]

**Comment by anvddriesch** [comment]
What is the status here? Can it either be merged or tagged as we did we cluster-operator so we can use it in our CAPA test release?

**Comment by rossf7** [comment]
> What is the status here? Can it either be merged or tagged as we did we cluster-operator so we can use it in our CAPA test release?

@anvddriesch @kubasobon Could we tag it for now?

We need to be sure this also works with existing clusters. I think we can do this by setting values in the cluster configmap for chart-operator.

**Comment by anvddriesch** [comment]
You mean simply tag it with something like `x.x.x-capi` as we did with cluster-operator? That's completely fine from my side. Then we an only use it in CAPI releases and it doesn't have to work with other clusters yet.

**Comment by rossf7** [comment]
@anvddriesch Yes, I think we could tag it as `2.11.0-capi` as the changes are based on that release.

This is fine for k8s 1.19. For 1.20 we need at least `2.13.1` as there was a problem with operatorkit.

@kubasobon WDYT?

**Comment by anvddriesch** [comment]
k8s 1.19 is the version we currently use for the CAPA test release so that's fine. :D

**Comment by kubasobon** [comment]
On it.

**Comment by kubasobon** [comment]
https://github.com/giantswarm/chart-operator/releases/tag/v2.11.0-capi-1

**Comment by rossf7** [comment]
@kubasobon Same this is also done. Changes were released in chart-operator 2.16.0.

**Pull request closed without merging**
