### PR TITLE
uses architect rendering for chart yaml version

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/3313. Just a preparation PR. Must not be merged just yet. We have to sort `architect` first.

### CODE REVIEW

**Comment by rossf7** [comment]
@xh3b4sd This looks stale. Can it be closed?

**Comment by xh3b4sd** [comment]
When this is not needed for `voo` we can close.

**Comment by rossf7** [comment]
I don't fully get the reason for the change. It was probably to avoid needing to bump the version in the chart.yaml by adding the SHA.

We have a fix for that in other charts. So maybe we can just do that here?

https://github.com/giantswarm/kubernetes-nginx-ingress-controller/blob/589cdb54810b2e9cc388e7ceb4f1a98ff6736901/helm/kubernetes-nginx-ingress-controller-chart/Chart.yaml#L5

**Comment by kopiczko** [comment]
No we don't need the SHA. And we probably will have to go with @indyfree early stage solution.

**Pull request closed without merging**
