### PR TITLE
Vendor update

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#2844

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Note that CI is failing.

**Comment by rossf7** [comment]
CI is fixed it needed updating for the e2e-harness changes.

**Comment by xh3b4sd** [comment]
Can we go with this?

**Comment by xh3b4sd** [comment]
Ah. :D

**Comment by rossf7** [comment]
Yes done now!

**Pull request merged**
