### PR TITLE
Applying Helm3

### PR DESCRIPTION
**Pull request by tomahawk28**

### CODE REVIEW

**Comment by tomahawk28** [comment]
@rossf7 updating `helm3` branch ain't that help to minimize the changes. I think we need to perform rebase or creating another branch

**Comment by tomahawk28** [comment]
Creating a draft PR for a cleaner view. https://github.com/giantswarm/chart-operator/pull/443

**Comment by rossf7** [comment]
Can we close this and https://github.com/giantswarm/chart-operator/pull/443? 

As we know we can create a PR from a fresh branch when we're ready to merge to master.

**Comment by tomahawk28** [comment]
Sure let's close this

**Pull request closed without merging**
