### PR TITLE
Change 'initialBootstrapMode' config name to 'bootstrapMode'

### PR DESCRIPTION
**Pull request by fiunchinho**
## Checklist

- [X] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by stone-z** [comment]
:wave: I'd like to get https://github.com/giantswarm/chart-operator/pull/902 in too if you're going to do a release with this soon

**Comment by fiunchinho** [comment]
> wave ~I'd like to get #902 in too if you're going to do a release with this soon~
> 
> edit: done

Let's release everything on Monday?

**Comment by stone-z** [comment]
> > wave ~I'd like to get #902 in too if you're going to do a release with this soon~
> > edit: done
> 
> Let's release everything on Monday?

No hurry from me, just didn't want to miss the release because of our timezone difference :slightly_smiling_face:

**Review by kopiczko — APPROVED** [review]

**Comment by fiunchinho** [comment]
I need an approval from the `CODEOWNERS`. If someone from @giantswarm/team-honeybadger could take a look, that'd be great.

**Pull request merged**
