### PR TITLE
Use release actual state instead of CR state

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/4326

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@giantswarm/team-batman i'm gonna need a pointer on how to deploy this. just merge? just merge and update the chart version? another thing?

**Comment by kopiczko** [comment]
Please check my comment here https://github.com/giantswarm/giantswarm/issues/4326#issuecomment-440343977

**Comment by xh3b4sd** [comment]
This looks like it should start to make use of the `exporterkit` collector set.

**Comment by JosephSalisbury** [comment]
@kopiczko answered in the main issue. we can discuss there if needed.

@xh3b4sd totally agree. it's in the refactoring list (https://github.com/giantswarm/giantswarm/issues/4462), and I'm happy to take it next. i'm strapped for time this week, so I wanted to fix the PM first, before taking on that work.

**Comment by MarcelMue** [comment]
Is this what we want? Everything that uses the tiller which `chart-operator` uses will be caught by this. That also means that at the very least on host cluster we will cover all deployments with this. It feels weird to me to have `chart-operator` report metrics on helm charts it doesn't manage.

**Comment by kopiczko** [comment]
Good comment from @MarcelMue. I understand reasoning in your comment in the issue @JosephSalisbury but I still would use `ChartConfig` status myself.

**Comment by JosephSalisbury** [comment]
That's a good point, I forgot about chart-operator on the control plane. I'll have a think.

**Comment by MarcelMue** [comment]
It could in theory also happen if a customer uses the tiller inside the giantswarm namespace in guest clusters. I don't think anyone does this currently though.

**Comment by JosephSalisbury** [comment]
Needs a rethink. Closing here.

**Pull request closed without merging**
