### PR TITLE
Push and use china registry

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/7435

### CODE REVIEW

**Comment by xh3b4sd** [comment]
E2E is fucky.

**Comment by calvix** [comment]
@rossf7  sure I can leave it for tomorrow, ping me when its fixed so i can rebase

**Comment by rossf7** [comment]
@calvix Thanks will do.

**Comment by rossf7** [comment]
@calvix e2e is fixed. You'll need to rebase.

**Comment by calvix** [comment]
nice and green :) good job @rossf7

**Pull request merged**
